function writeMeshDataINP(filename_mesh,point_list,element_list,element_type)
% write mesh data into inp file(ABAQUS analysis format)
%
if strcmp(filename_mesh(end-3:end),'.inp')
    filename_mesh=filename_mesh(1:end-4);
end

file_mesh=fopen([filename_mesh,'.inp'],'w');

% write basic information of inp file
fprintf(file_mesh,'*Heading\n');
fprintf(file_mesh,'** Job name: Job-%s Model name: Model-%s\n',filename_mesh,filename_mesh);
fprintf(file_mesh,'** Generated by: matlab::writeMeshDataINP\n');
fprintf(file_mesh,'*Preprint, echo=NO, model=NO, history=NO, contact=NO\n');

% write start of part
fprintf(file_mesh,'**\n');
fprintf(file_mesh,'** PARTS\n');
fprintf(file_mesh,'**\n');

% write part name
fprintf(file_mesh,'*Part, name=Part-%s\n',filename_mesh);

% write part point data
fprintf(file_mesh,'*Node\n');
[point_number,~]=size(point_list);
for point_index=1:point_number
    fprintf(file_mesh,'% 7d',point_index);
    for dimension_index=1:3
        fprintf(file_mesh,',% 14f',point_list(point_index,dimension_index));
    end
    fprintf(file_mesh,'\n');
end

% write element data
fprintf(file_mesh,'*Element, type=%s\n',element_type);
[element_number,node_number]=size(element_list);
node_number=node_number-1;
for element_index=1:element_number
    fprintf(file_mesh,'% 4d',element_index);
    for node_index=1:node_number
        fprintf(file_mesh,',% 4d',element_list(element_index,node_index));
    end
    fprintf(file_mesh,'\n');
end

% end part
fprintf(file_mesh,'*End Part\n');
fprintf(file_mesh,'**\n');

% write start of assembly
fprintf(file_mesh,'**\n');
fprintf(file_mesh,'** ASSEMBLY\n');
fprintf(file_mesh,'**\n');

% import part
fprintf(file_mesh,'*Assembly, name=Assembly\n');
fprintf(file_mesh,'**  \n');
fprintf(file_mesh,'*Instance, name=Part-%s-1, part=Part-%s\n',filename_mesh,filename_mesh);
fprintf(file_mesh,'*End Instance\n');
fprintf(file_mesh,'**\n');

% write end of assembly
fprintf(file_mesh,'*End Assembly\n');

fclose(file_mesh);
clear('file_mesh');

end