function writeMeshINP(mesh_filestr,grid,marker_name_list)
% write mesh data into inp file(ABAQUS analysis format)
%
% input:
% filename_mesh, grid
%
% notice:
% grid(single zone): grid.name, grid.point_list, grid.(marker)
% marker: marker.type, marker.element_list, marker.number_list, marker.ID_list
% notice: marker which has the same name of file is volume element
%
if nargin < 3
    marker_name_list=[];
end
if isempty(marker_name_list)
    marker_name_list=fieldnames(grid);
end

% cheak filename
if length(mesh_filestr) > 4
    if ~strcmpi(mesh_filestr((end-3):end),'.inp')
        mesh_filestr=[mesh_filestr,'.inp'];
    end
else
    mesh_filestr=[mesh_filestr,'.inp'];
end

file_mesh=fopen(mesh_filestr,'w');

% write basic information of inp file
fprintf(file_mesh,'*Heading\n');
fprintf(file_mesh,'** Job name: Job-%s Model name: Model-%s\n',mesh_filestr,mesh_filestr);
fprintf(file_mesh,'** Generated by: matlab::writeMeshDataINP\n');
fprintf(file_mesh,'*Preprint, echo=NO, model=NO, history=NO, contact=NO\n');

% write start of part
fprintf(file_mesh,'**\n');
fprintf(file_mesh,'** PARTS\n');
fprintf(file_mesh,'**\n');

% write all part
point_list=grid.point_list;
for marker_index=1:length(marker_name_list)
    marker_name=marker_name_list{marker_index};
    if strcmp(marker_name,'point_list') || strcmp(marker_name,'name')
        continue;
    end

    % write part name
    fprintf(file_mesh,'*Part, name=%s\n',marker_name);

    % notice, element index in each part of inp file start from 1
    % search min and max element index of mesh
    element_list=grid.(marker_name).element_list;
    number_list=grid.(marker_name).number_list;
    ID_list=grid.(marker_name).ID_list;

    min_node_index=min(min(element_list));
    max_point_index=max(max(element_list));

    % write part point data
    fprintf(file_mesh,'*Node\n');
    for point_index=min_node_index:max_point_index
        fprintf(file_mesh,'% 7d',point_index-min_node_index+1);
        for dimension_index=1:3
            fprintf(file_mesh,',% 14f',point_list(point_index,dimension_index));
        end
        fprintf(file_mesh,'\n');
    end

    % write element data
    % notice, element index in each part of inp file start from 1
    if strcmp(grid.(marker_name).type,'MIXED2') || strcmp(grid.(marker_name).type,'MIXED3')
        element_number=numel(ID_list);
        [ID_list,index_list]=sort(ID_list);
        map_list=sort(index_list);
        node_index_list=cumsum(number_list);

        % sort element_list
        element_list_old=element_list;
        node_index=0;
        for element_index=1:element_number
            node_number=number_list(map_list(element_index));
            element_list(node_index+(1:node_number))=element_list_old...
                (node_index_list(map_list(element_index))-(node_number:-1:1)+1);
            node_index=node_index+node_number;
        end

        number_list=number_list(index_list);
        id=ID_list(1);
        
        fprintf(file_mesh,'*Element, type=%s\n',typeINPID(id));
        node_index=0;
        for element_index=1:element_number
            % if element type change, state new type
            if ID_list(element_index) ~= id
                id=ID_list(element_index);
                fprintf(file_mesh,'*Element, type=%s\n',typeINPID(id));
            end

            fprintf(file_mesh,'% 4d',element_index);
            node_number=number_list(element_index);

            for index=1:node_number
                fprintf(file_mesh,',% 4d',element_list(index+node_index)-min_node_index+1);
            end
            node_index=node_index+node_number;

            fprintf(file_mesh,'\n');
        end

    else
        fprintf(file_mesh,'*Element, type=%s\n',typeINPID(ID_list));

        [element_number,node_number]=size(element_list);
        for element_index=1:element_number
            fprintf(file_mesh,'% 4d',element_index);
            for node_index=1:node_number
                fprintf(file_mesh,',% 4d',element_list(element_index,node_index)-min_node_index+1);
            end
            fprintf(file_mesh,'\n');
        end
    end

    % end part
    fprintf(file_mesh,'*End Part\n');
    fprintf(file_mesh,'**\n');
end

% write start of assembly
fprintf(file_mesh,'**\n');
fprintf(file_mesh,'** ASSEMBLY\n');
fprintf(file_mesh,'**\n');
fprintf(file_mesh,'*Assembly, name=Assembly\n');

% import part
for marker_index=1:length(marker_name_list)
    marker_name=marker_name_list{marker_index};
    if strcmp(marker_name,'point_list') || strcmp(marker_name,'name')
        continue;
    end
    
    fprintf(file_mesh,'**  \n');
    fprintf(file_mesh,'*Instance, name=Part-%s-1, part=Part-%s\n',marker_name,marker_name);
    fprintf(file_mesh,'*End Instance\n');
    fprintf(file_mesh,'**\n');
end

% write end of assembly
fprintf(file_mesh,'*End Assembly\n');

fclose(file_mesh);
clear('file_mesh');

end

function type=typeINPID(id)
switch id
    case 3
        type='B31';
    case 5
        type='S3';
    case 7
        type='S4';
    case 10
        type='C3D4I';
    case 17
        type='C3D8I';
    otherwise
        error('idType: unknown identifier')
end
end
